django/00_django_intro/firstpjt/articles/urls.py
from django.urls import path
# 명시적 상대경로 표현
from . import views

app_name = 'articles'
urlpatterns = [
    path('index/', views.index, name='index'),
    path('greeting/', views.greeting, name='greeting'),
    path('dinner/', views.dinner, name='dinner'),
    path('throw/', views.throw, name='throw'),
    path('catch/', views.catch, name='catch'),
    path('hello/<str:name>/', views.hello, name='hello'),
    # 주소자체를 변수로 설정하여 동적으로 작동
    # path('hello/<name>/', views.hello),
    # 'articles/1/'로 요청했을 경우 뷰 함수의 detail 수행
    path('<int:article_num>', views.detail, name='article_num'),
    path('dtl-practice/', views.dtl_practice, name='dtl_preactice'),
]

django/00_django_intro/firstpjt/firstpjt/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    # 주소가 index로 들어온다면 articles 패키지안에 views 모듈의 index함수 실행
    path('articles/', include('articles.urls')),
    path('pages/', include('pages.urls')),
]

django/00_django_intro/firstpjt/pages/urls.py
from django.urls import path
from . import views

app_name = 'pages'
urlpatterns = [
    path('index/', views.index, name='index')
]

django/00_django_intro/firstpjt/articles/views.py
import random
from django.shortcuts import render

# Create your views here.
def index(request): # 첫번째 인자는 반드시 request
    # templates 경로안에 있어야한다. T는
    return render(request, 'articles/index.html')    # render 함수의 첫번째 인자는 request

def greeting(request):
    foods = ['apple', 'banana', 'coconut',]
    info = {
        'name': 'Harry'
    }
    context = {
        'info': info,
        'foods': foods,
    }

    return render(request, 'articles/greeting.html', context)

def dinner(request):
    foods = ['족발', '피자', '햄버거', '초밥',]
    pick = random.choice(foods)
    context = {
        'pick': pick,
        'foods': foods,
    }
    return render(request, 'articles/dinner.html', context)

def throw(request):
    return render(request, 'articles/throw.html')

def catch(request):
    # request에서 get에 위치해 있어. 위치해있는 값은 dict이여서 key인 message로 접근
    message = request.GET.get('message')
    context = {
        'message': message,
    }
    return render(request, 'articles/catch.html', context)

def hello(request, name):
    context = {
        'name': name,
    }
    return render(request, 'articles/hello.html', context)

def detail(request, article_num):
    context = {
        'article_num': article_num
    }
    return render(request, 'articles/detail.html', context)

def dtl_practice(request):
    students = ['민찬우', '민준우', '이현지', '이상민']
    fruits = ['사과', '바나나', '포도', '감', '수박']
    user_list = []
    context = {
        'students': students,
        'fruits': fruits,
        'user_list': user_list,
    }

    return render(request, 'articles/dtl_practice.html', context)

django/00_django_intro/firstpjt/pages/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'pages/index.html')

django/00_django_intro/firstpjt/articles/templates/articles/catch.html
{% extends 'base.html' %}

{% block content %}
  <h1>CATCH</h1>
  <h2>여기서 {{ message }}를 받았어.</h2>

  <a href="{% url 'articles:throw' %}">다시 던지러!</a>
{% endblock content %}

django/00_django_intro/firstpjt/articles/templates/articles/detail.html
{% extends 'base.html' %}

{% block content %}
  <h1>{{ article_num }}게시글 정보</h1>

  <a href="{% url 'index' %}">index로 돌아가기</a>
{% endblock content %}

django/00_django_intro/firstpjt/articles/templates/articles/dinner.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>오늘 저녁은 {{ pick }}!!</h1>
  <p>{{ pick }}은 {{ pick|length }}</p>
  <p>메뉴판</p>
  <ul>
    {% for food in foods %}
      <li>{{ food }}</li>
    {% endfor %}
  </ul>
  
  {# 이것은 주석입니다. #}
  
  {% comment %}
    <p>1</p>
    <p>2</p>
    <p>3</p>
  {% endcomment %}
</body>
</html>

django/00_django_intro/firstpjt/articles/templates/articles/dtl_practice.html
{% extends 'base.html' %}

{% block content %}
  <h1>DTL 연습 페이지</h1>
  <hr>
  <h3>1. for</h3>
  {% for student in students %}
    <p>{{ student }}</p>
  {% endfor %}

  {% for fruit in fruits %}
    <p>{{ forloop.counter0 }}{{ fruit }}</p>
  {% endfor %}

  {% for user in user_list %}
    <p>{{ user }}</p>
  {% empty %}
    <p>user가 없습니다.</p>
  {% endfor %}


  <h3>2. if</h3>
  {% if '민찬우' in students %}
    <p>민찬우님 계시네요.</p>
  {% endif %}

  {% for student in students %}
    {% if forloop.first %}
      <p>첫번째 학생은 {{ student }}님 입니다.</p>
    {% else %}
      <p>{{ student }}</p>
    {% endif %}
  {% endfor %}

  <hr>
  <h3>3. Length Filter</h3>

  <p>{{ student|length }}</p>
  {% for fruit in fruits %}
    {% if fruit|length > 2 %}
      <p>{{ fruit }} 이름이 길어요</p>
    {% else %}
      <p>{{ fruit }} 이름이 적당해요</p>
    {% endif %}
  {% endfor %}



  <hr>
  <p>4. Lorem</p>
  <p>{% lorem 5 %}</p>
  <p>{% lorem 5 w %}</p>
  <p>{% lorem 5 w random %}</p>

  <hr>
  <p>5. 글자필터</p>
  <p>{{ 'CHANWOO'|lower }}</p>
  <p>{{ 'min chan woo'|title }}</p>

  <hr>
  <h3>6. 연산</h3>
  <p>{{ 4|add:6 }}</p>

  <hr>
  <h3>7. 날짜</h3>
  {% comment %} 현재 시간을 여러 형태로 바꿔서 보여주기 {% endcomment %}
  <p>{% now "DATETIME_FORMAT" %}</p>
  <p>{% now "SHORT_DATETIME_FORMAT" %}</p>
  <p>{% now "DATE_FORMAT" %}</p>
  <p>{% now "SHORT_DATE_FORMAT" %}</p>
  <hr>
  {% now "Y년 m월 d일 h:i" %}

  {% comment %} 출력 결과를 변수로 저장해서 활용하기 {% endcomment %}
  {% now "Y" as current_year %}
  <p>{{ current_year }}</p>
{% endblock %}

django/00_django_intro/firstpjt/articles/templates/articles/greeting.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>안녕하세요. 저는 {{ info.name }} 입니다.</h1>
  <p>제가 좋아하는 음식은 {{ foods }}입니다.</p>
  <p>그 중 {{ foods.0 }}을 가장 좋아합니다.</p>
</body>
</html>

django/00_django_intro/firstpjt/articles/templates/articles/hello.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <h1>Hello</h1>
  <h2>만나서 반가워요 {{ name }}님!!</h2>
</body>
</html>

django/00_django_intro/firstpjt/articles/templates/articles/index.html
{% extends 'base.html' %}

{% block content %}
  <h1>만나서 반가워요!!!</h1>
  <a href="{% url 'articles:greeting' %}">greeting</a>
  <a href="{% url 'articles:dinner' %}">dinner</a>
  <a href="{% url 'articles:throw' %}">throw</a>
  <hr>
  <a href="{% url 'pages:index' %}">Pages의 Index 페이지로 이동하기</a>
{% endblock content %}

django/00_django_intro/firstpjt/articles/templates/articles/throw.html
{% extends 'base.html' %}

{% block content %}
  <h1>THROW</h1>
  <form action="{% url 'articles:catch' %}" method="GET">
    <label for="message">Throw: </label>
    <input type="text" name="message" id="message">
    <label for="message2">Throw2: </label>
    <input type="text" name="message2" id="message2">
    <input type="submit">
  </form>

{% endblock content %}

django/00_django_intro/firstpjt/articles/templates/catch.html
{% extends 'base.html' %}

{% block content %}
  <h1>CATCH</h1>
  <h2>여기서 {{ message }}를 받았어.</h2>

  <a href="{% url 'throw' %}">다시 던지러!</a>
{% endblock content %}

django/00_django_intro/firstpjt/articles/templates/throw.html
{% extends 'base.html' %}

{% block content %}
  <h1>THROW</h1>
  <form action="{% url 'catch' %}" method="GET">
    <label for="message">Throw: </label>
    <input type="text" name="message" id="message">
    <input type="submit">
  </form>

{% endblock content %}

django/00_django_intro/firstpjt/pages/templates/pages/index.html
{% extends 'base.html' %}

{% block title %}
PAGES INDEX
{% endblock %}

{% block content %}
<h2>Pages의 Index 페이지입니다.</h2>
{% endblock  %}